PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZABAP003_T_SY_PM-BNAME .
    FIELD ZABAP003_T_SY_PM-TERMINAL .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZABAP003_T_SY_PM-BNAME .
  module detail_pai.
 endchain.
